# Generated by Django 5.1.7 on 2025-04-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripcion',
            new_name='description',
        ),
    ]
