# Generated by Django 5.1.7 on 2025-04-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autor',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
